"""
Django settings for Scrapping_POC project.

Generated by 'django-admin startproject' using Django 1.8.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
import djcelery

djcelery.setup_loader()

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'u#%0a0&i4sv3@y1(+cwyx0(fp5t=%9$lp(6lj7r$v-y9h^8a-('

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'crawler',
    'djcelery',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'Scrapping_POC.urls'
CELERY_RESULT_BACKEND = "amqp"
CELERY_IMPORTS = ("crawler.tasks", )
CELERY_ALWAYS_EAGER = True

BROKER_HOST = "localhost"
BROKER_PORT = 5672
BROKER_PASSWORD = "scraper"
BROKER_USER = "scraper"
BROKER_VHOST = "localhost"
BROKER_URL = "amqp://scraper:scraper@localhost:5672/localhost"

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Scrapping_POC.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'scrapper',
        'USER': 'scrapper',
        'PASSWORD': 'otv0n9bazFHuH4ICSmVTlR5aXUzTN8p1pJRDIRB7k8pP0YfH81qjGlit4HaHFnyU',
        'HOST': 'localhost',
        'PORT': '',
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Calcutta'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'

from celery.schedules import crontab

# The default Django db scheduler
CELERYBEAT_SCHEDULER = "djcelery.schedulers.DatabaseScheduler"
CELERYBEAT_SCHEDULE = {
    "housing-officials": {
        "task": "crawler.tasks.housing_officials",
        # Every Sunday at 4:30AM
        "schedule": crontab(minute="*/41"),
        "args": (),
    },
    "magicbricks-officials": {
        "task": "crawler.tasks.magicbricks_officials",
        # Every Sunday at 4:30AM
        "schedule": crontab(minute="*/46"),
        "args": (),
    },
    "propertywala-officials": {
        "task": "crawler.tasks.propertywala_officials",
        # Every Sunday at 4:30AM
        "schedule": crontab(minute="*/51"),
        "args": (),
    },
    "sulekha-officials": {
        "task": "crawler.tasks.sulekha_officials",
        # Every Sunday at 4:30AM
        "schedule": crontab(minute="*/57"),
        "args": (),
    },
}
